

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8084/eureka/


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
spring:
  application:
   name: Config-Prod
   
